name: neanno

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.6
  - pip
  - pytorch>=1.7.0
  - pip:
      - pyyaml>=5.3.1
      - config>=0.5.0
      - PyQt5>=5.12.2
      - pandas>=1.1.4
      - scikit-learn>=0.23.2
      - numpy==1.19.3      
      - flashtext>=2.7
      - cerberus>=1.3.2
      - seaborn>=0.11.0
      - spacy>=2.3.4
      - spacy-transformers>=0.6.2
      - spacy-lookups-data>=0.3.2

# note: check https://spacy.io/usage for model installation,
# eg. python -m spacy download en_vectors_web_lg